fb_logrotate: sanity check overlapping configs
Summary:
Having two configurations for the same file breaks logrotate:

```
[...]
error: fb_logrotate.conf:87 duplicate log entry for /var/facebook/logs/foo.log
[...]
rotating pattern: /var/facebook/logs/bar/*.log  73400320 bytes (5 rotations)
empty log files are not rotated, old logs are removed
No logs found. Rotation not needed.
```

This adds a `ruby_block` to validate the hash contents and fail in case there it overlapping.

Reviewed By: patcox

Differential Revision: D9231099

fbshipit-source-id: e34f1e736129db9c78371fa5e8e7687642730f42