fb_fstab: Support for multiple bind mounts
Summary:
If you bind mount the same device against multiple mount_points fb_fstab will fail, this fixes that issue.

Landed D4965982 with this change but had to roll back because of:

{"chef.run_exception":"NoMethodError: whyrun_safe_ruby_block[validate data] (fb_fstab::default line 28) had an error: NoMethodError: undefined method `split' for nil:NilClass"}

checking if data[opts] contains something this time.

Reviewed By: jaymzh

Differential Revision: D4987122

fbshipit-source-id: 3f59e5bb1fa3e0ce135e4aa47d27e8e84c0e0f74