Add missing requires shellwords
Summary:
We need shellwords to run x.shellescape

hit this on some machines with super old chef runs:

   19:        # Chef clients older than v13.3.10 have a bug in the service resource
   20:        # https://github.com/chef/chef/pull/6230
   21:        # so we workaround it here by calling shellescape
   22:        if FB::Version.new(Chef::VERSION) < FB::Version.new('13.3.10')
   23>>         return s.shellescape
   ...
   FATAL: NoMethodError: undefined method `shellescape' for "dev-sda3.swap":String

Reviewed By: jaymzh

Differential Revision: D6659243

fbshipit-source-id: 2edc229623e32617b393a99004c73a0353ba42a0