fb_network_scripts: chef 14 compliant
Summary:
Provisioning chef runs need to restart the network and host interfaces. On chef 14 they will fail with the following error

```
NoMethodError
-------------
undefined method `updated_by_last_action' for #<#<Class:0x0000000003e9ea50>:0x000000000739afb0>

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/fb_network_scripts/resources/redhat_interface.rb:287:in `block in class_from_file'
```

Reviewed By: joshuamiller01

Differential Revision: D29284933

fbshipit-source-id: ff3867c737f935025175151d5a3e1e08dd9d855f